### ISSUE TITLE
`__del__` method in `KPZ101` class error

### ISSUE THREAD

**Issue by claudiojar** [Schlabonski/cubini#2]
The `__del__(self)` method calls for `#self.com.disconnect()` which calls `self.device.attach_kernel_driver(0)` in `vcp_terminal.py` which calls `self._ctx.backend.attach_kernel_driver()` in `core.py`. The `attach_kernel_driver()` method is not implemented in the `core.py` and raises a `Not_Implemented` exception when called.\
This bug appears to be because `core.py` is not up to date ? Any known solutions ? 

I tried a ''hack'' by simply commenting out the line ant it seems to work so far... but it is not ideal.

Found this similar problem being discussed [here](https://pyusb-users.narkive.com/mC840N9D/confusion-with-attach-kernel-driver-method-in-pyusb-1-0-0b2) but it does not seem to apply in this case. 

PyUSB(v1.2.1) and LibUSB (v1.0.24) all up to date, installed via anaconda. Using Python 3.8.12 on Windows 10 64-bit.

**Comment by Schlabonski** [comment]
Hi Claudio,

I have only tested this library on linux. I have another project based on libusb that I also tested on windows. Using libusb in this case needed some additional steps that I put into the [readme](https://github.com/Schlabonski/evalcontrol). Maybe this could help you? Currently I have no Windows machine available to reproduce your issue.

**Comment by claudiojar** [comment]
Dear Fabian, 
Thank you for your message, I have followed the steps explained in the README and the problem persists. I will investigate further and comment again once I have more information. 

Thank you for your help.

**Comment by claudiojar** [comment]
Dear Fabian, I replicated the issue on Linux (Ubuntu 20.04) and was not able to fix it, I decided to move on. Apologies for the inconvenience, I will close the issue now.
